service: petstore

provider:
  name: aws
  runtime: java8
  memorySize: 1512
  timeout: 60
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'us-west-2'}  
  profile: ${opt:profile, "default"}

resources:
  Description: Example Pet Store API written with SpringBoot with the aws-serverless-java-container library

functions:
  SpringBootPetStoreApi:
    # CodeUri: target/serverless-spring-boot-example-1.0-SNAPSHOT-lambda-package.zip
    # Policies: AWSLambdaBasicExecutionRole
    handler: com.amazonaws.serverless.sample.springboot.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY